# Part of Odoo. See LICENSE file for full copyright and licensing details.

SHOPIFY_API_VERSION = '2026-01'

# graphql url used for retrive numaric id from global id of associated object.
GLOBAL_PRODUCT_ID = "gid://shopify/Product/"
GLOBAL_PRODUCT_VARIANT_ID = "gid://shopify/ProductVariant/"
GLOBAL_LOCATION_ID = "gid://shopify/Location/"
GLOBAL_CUSTOMER_ID = "gid://shopify/Customer/"
GLOBAL_FULFILLMENT_ID = "gid://shopify/Fulfillment/"
GLOBAL_FULFILLMENT_LINE_ITEM_ID = "gid://shopify/FulfillmentLineItem/"
GLOBAL_LINE_ITEM_ID = "gid://shopify/LineItem/"
GLOBAL_SHIPPING_LINE_ID = "gid://shopify/ShippingLine/"
GLOBAL_ORDER_ID = "gid://shopify/Order/"
GLOBAL_INVENTORY_ITEM_ID = "gid://shopify/InventoryItem/"

# Mapping of Shopify Carrier Names
SHOPIFY_CARRIER_NAMES_MAPPING = {
    "4px": "4PX",
    "ags": "AGS",
    "amazon": "Amazon",
    "amazonlogisticsuk": "Amazon Logistics UK",
    "anpost": "An Post",
    "anjunlogistics": "Anjun Logistics",
    "apc": "APC",
    "asendiausa": "Asendia USA",
    "australiapost": "Australia Post",
    "bonshaw": "Bonshaw",
    "bpost": "BPost",
    "bpostinternational": "BPost International",
    "canadapost": "Canada Post",
    "canpar": "Canpar",
    "cdllastmile": "CDL Last Mile",
    "chinapost": "China Post",
    "chronopost": "Chronopost",
    "chukou1": "Chukou1",
    "colissimo": "Colissimo",
    "comingle": "Comingle",
    "coordinadora": "Coordinadora",
    "correios": "Correios",
    "correos": "Correos",
    "ctt": "CTT",
    "cttexpress": "CTT Express",
    "cypruspost": "Cyprus Post",
    "delnext": "Delnext",
    "deutschepost": "Deutsche Post",
    "dhlecommerce": "DHL eCommerce",
    "dhlecommerceasia": "DHL eCommerce Asia",
    "dhlexpress": "DHL Express",
    "dpd": "DPD",
    "dpdlocal": "DPD Local",
    "dpduk": "DPD UK",
    "dtdexpress": "DTD Express",
    "dx": "DX",
    "eagle": "Eagle",
    "estes": "Estes",
    "evri": "Evri",
    "fedex": "FedEx",
    "firstgloballogistics": "First Global Logistics",
    "firstline": "First Line",
    "fsc": "FSC",
    "fulfilla": "Fulfilla",
    "gls": "GLS",
    "guangdongweisuyiinformationtechnology_wse": "Guangdong Weisuyi Information Technology (WSE)",
    "heppnerinternationalespeditiongmbh&co.": "Heppner Internationale Spedition GmbH & Co.",
    "icelandpost": "Iceland Post",
    "idex": "IDEX",
    "israelpost": "Israel Post",
    "japanpost_en": "Japan Post (EN)",
    "japanpost_ja": "Japan Post (JA)",
    "lapostecolissimo": "La Poste Colissimo",
    "laposteburkinafaso": "La Poste Burkina Faso",
    "lasership": "Lasership",
    "latviapost": "Latvia Post",
    "lietuvospaštas": "Lietuvos Paštas",
    "logisters": "Logisters",
    "lonestarovernight": "Lone Star Overnight",
    "m3logistics": "M3 Logistics",
    "meteorspace": "Meteor Space",
    "mondialrelay": "Mondial Relay",
    "newzealandpost": "New Zealand Post",
    "ninjavan": "NinjaVan",
    "northrussiasupplychain_shenzhen_co.": "North Russia Supply Chain (Shenzhen) Co.",
    "ontrac": "OnTrac",
    "packeta": "Packeta",
    "pagologistics": "Pago Logistics",
    "pingandatengfeiexpress": "Ping An Da Tengfei Express",
    "pitneybowes": "Pitney Bowes",
    "portalpostnord": "Portal PostNord",
    "posteitaliane": "Poste Italiane",
    "postnl": "PostNL",
    "postnorddk": "PostNord DK",
    "postnordno": "PostNord NO",
    "postnordse": "PostNord SE",
    "purolator": "Purolator",
    "qxpress": "Qxpress",
    "qyunexpress": "Qyun Express",
    "royalmail": "Royal Mail",
    "royalshipments": "Royal Shipments",
    "sagawa_en": "Sagawa (EN)",
    "sagawa_ja": "Sagawa (JA)",
    "sendle": "Sendle",
    "sfexpress": "SF Express",
    "sfcfulfillment": "SFC Fulfillment",
    "shreenandancourier": "SHREE NANDAN COURIER",
    "singaporepost": "Singapore Post",
    "southwestaircargo": "Southwest Air Cargo",
    "startrack": "StarTrack",
    "stepforwardfreight": "Step Forward Freight",
    "swisspost": "Swiss Post",
    "tforcefinalmile": "TForce Final Mile",
    "tinghao": "Tinghao",
    "tnt": "TNT",
    "tollipec": "Toll IPEC",
    "uniteddeliveryservice": "United Delivery Service",
    "ups": "UPS",
    "usps": "USPS",
    "venipak": "Venipak",
    "wepost": "We Post",
    "whistl": "Whistl",
    "wizmo": "Wizmo",
    "wmyc": "WMYC",
    "xpedigo": "Xpedigo",
    "xpologistics": "XPO Logistics",
    "yamato_en": "Yamato (EN)",
    "yamato_ja": "Yamato (JA)",
    "yifanexpress": "YiFan Express",
    "yunexpress": "YunExpress",
}
